ALTER TABLE empresa
    ADD COLUMN endereco VARCHAR(255),
    ADD COLUMN pago BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN cadastro DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN vencimento INTEGER NOT NULL CHECK (vencimento BETWEEN 1 AND 31) default 5;
